name: mistrioncall
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fl_chart: ^0.41.0
  charts_flutter: ^0.12.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_rating_bar: ^4.0.1
  firebase_crashlytics: ^3.4.9
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/font/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/font/WorkSans-Regular.ttf
        - asset: assets/font/WorkSans-SemiBold.ttf
          weight: 600

