// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJaI3t2a_liGpFUPVIdtYzyAw0hRrBmU',
    appId: '1:585014761693:web:f31c4aff9f10afc6266334',
    messagingSenderId: '585014761693',
    projectId: 'userapp-8e244',
    authDomain: 'userapp-8e244.firebaseapp.com',
    storageBucket: 'userapp-8e244.appspot.com',
    measurementId: 'G-F20X7CS7P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQSoVzDcg6G_lzo6y9nyuXscl-nCamAQ',
    appId: '1:585014761693:android:2279bdc7c3ceb9f6266334',
    messagingSenderId: '585014761693',
    projectId: 'userapp-8e244',
    storageBucket: 'userapp-8e244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4CNewQBXJEMW_9DxWbc1WHyYaxnLAq0',
    appId: '1:585014761693:ios:55eaee49fb7453aa266334',
    messagingSenderId: '585014761693',
    projectId: 'userapp-8e244',
    storageBucket: 'userapp-8e244.appspot.com',
    iosClientId: '585014761693-aeg1krj8dkolrt5nk0pcnc2svt5qr2kq.apps.googleusercontent.com',
    iosBundleId: 'com.iqonic.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa4CNewQBXJEMW_9DxWbc1WHyYaxnLAq0',
    appId: '1:585014761693:ios:b7fa67b4eb90d65b266334',
    messagingSenderId: '585014761693',
    projectId: 'userapp-8e244',
    storageBucket: 'userapp-8e244.appspot.com',
    iosClientId: '585014761693-8ficm7hf0q21q0umpsk1dq21luir6peh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingSystemFlutter',
  );
}
